<?php
/**
 * Profile page
 */

require_once __DIR__ . '/php/helpers.php';

requireAuth();

$userId = getUserId();
$error = getFlash('error');
$success = getFlash('success');

// Get profile data
$profile = db()->fetchOne(
    "SELECT * FROM profiles WHERE id = ?",
    [$userId]
);

// Ensure default visibility settings exist to avoid undefined indexes
if ($profile) {
    if (!isset($profile['show_photo'])) {
        $profile['show_photo'] = 1;
    }
    if (!isset($profile['show_photo_pdf'])) {
        $profile['show_photo_pdf'] = 1;
    }
    if (!isset($profile['show_qr_code'])) {
        $profile['show_qr_code'] = $profile['show_photo'] ? 0 : 1;
    }
}

// Check if username is auto-generated (starts with "user" followed by 8 alphanumeric chars)
$isAutoGeneratedUsername = preg_match('/^user[a-z0-9]{8}$/i', $profile['username'] ?? '');

// Handle form submission
if (isPost()) {
    // Verify CSRF token
    $token = post(CSRF_TOKEN_NAME);
    if (!verifyCsrfToken($token)) {
        setFlash('error', 'Invalid security token. Please try again.');
        redirect('/profile.php');
    }

    // Helper to normalise profile text fields
    $normalise = function($value, $stripTags = true) {
        if (!is_string($value)) {
            return null;
        }
        $value = trim($value);
        if ($value === '') {
            return null;
        }
        return $stripTags ? strip_tags($value) : $value;
    };

    $data = [];

    $data['full_name'] = $normalise(post('full_name', ''));

    $phoneValue = $normalise(post('phone', ''), false);
    if ($phoneValue !== null) {
        $phoneValue = preg_replace('/[^0-9\+\-\s\(\)]/', '', $phoneValue);
    }
    $data['phone'] = $phoneValue;

    $data['location'] = $normalise(post('location', ''));

    $linkedinUrlInput = $normalise(post('linkedin_url', ''), false);
    $data['linkedin_url'] = $linkedinUrlInput;

    // For bio, allow plain text only (single line on CV, but store trimmed string)
    $data['bio'] = $normalise(post('bio', ''), true);

    // Handle show photo options (always include these fields if a photo exists)
    if (!empty($profile['photo_url'])) {
        $showPhotoCvInput = post('show_photo_cv', '0');
        $showPhotoCv = ($showPhotoCvInput === '1' || $showPhotoCvInput === 'on') ? 1 : 0;
        $data['show_photo'] = $showPhotoCv;

        $showPhotoPdfInput = post('show_photo_pdf', '0');
        $showPhotoPdf = ($showPhotoPdfInput === '1' || $showPhotoPdfInput === 'on') ? 1 : 0;
        $data['show_photo_pdf'] = $showPhotoPdf;

        // Automatically control QR code visibility for the digital CV: show QR when photo is hidden
        $data['show_qr_code'] = $showPhotoCv ? 0 : 1;
    } else {
        // No photo uploaded: ensure visibility flags are zero and QR code is enabled
        $data['show_photo'] = 0;
        $data['show_photo_pdf'] = 0;
        $data['show_qr_code'] = 1;
    }

    // Handle header colors
    $headerFromColor = trim(post('cv_header_from_color', ''));
    if ($headerFromColor !== '') {
        // Validate hex color
        if (preg_match('/^#[0-9A-Fa-f]{6}$/', $headerFromColor)) {
            $data['cv_header_from_color'] = $headerFromColor;
        }
    }

    $headerToColor = trim(post('cv_header_to_color', ''));
    if ($headerToColor !== '') {
        // Validate hex color
        if (preg_match('/^#[0-9A-Fa-f]{6}$/', $headerToColor)) {
            $data['cv_header_to_color'] = $headerToColor;
        }
    }

    // Username is required, so we must have it
    $username = trim(post('username', ''));
    if ($username === '') {
        setFlash('error', 'Username is required');
        redirect('/profile.php');
    }
    $data['username'] = strip_tags($username);

    $data['updated_at'] = date('Y-m-d H:i:s');

    // Validate username (it's required now)
    if (!preg_match('/^[a-z0-9][a-z0-9\-_]+$/', $data['username'])) {
        setFlash('error', 'Username can only contain lowercase letters, numbers, hyphens, and underscores');
        redirect('/profile.php');
    }

    // Check if username is already taken by another user
    $existing = db()->fetchOne(
        "SELECT id FROM profiles WHERE username = ? AND id != ?",
        [$data['username'], $userId]
    );

    if ($existing) {
        setFlash('error', 'Username is already taken');
        redirect('/profile.php');
    }

    // Validate LinkedIn URL if provided
    if (!empty($data['linkedin_url']) && !preg_match('/^https?:\/\//i', $data['linkedin_url'])) {
        $data['linkedin_url'] = 'https://' . ltrim($data['linkedin_url'], '/');
    }

    if (!empty($data['linkedin_url']) && !validateUrl($data['linkedin_url'])) {
        setFlash('error', 'Invalid LinkedIn URL');
        redirect('/profile.php');
    }

    // Check for XSS on all fields that are set
    foreach ($data as $field => $value) {
        if ($value === null) {
            continue;
        }
        if (in_array($field, ['full_name', 'location', 'username', 'bio', 'linkedin_url']) && checkForXss($value)) {
            setFlash('error', "Invalid content in {$field}");
            redirect('/profile.php');
        }
    }

    // Update profile
    try {
        // Ensure we have at least updated_at even if all fields null
        if (empty(array_filter($data, fn($value) => !is_null($value) && $value !== ''))) {
            $data = ['updated_at' => date('Y-m-d H:i:s')];
        } else {
            $data['updated_at'] = date('Y-m-d H:i:s');
        }

        $rowsAffected = db()->update('profiles', $data, 'id = ?', [$userId]);

        if ($rowsAffected > 0 || $rowsAffected === 0) { // 0 is okay if no actual changes
            setFlash('success', 'Profile updated successfully');
        } else {
            setFlash('error', 'No changes were saved');
        }
        redirect('/profile.php');
    } catch (PDOException $e) {
        // Log the full error for debugging
        error_log("Profile update error: " . $e->getMessage());
        error_log("SQL State: " . $e->getCode());
        error_log("User ID: " . $userId);
        error_log("Data being updated: " . print_r($data, true));

        // Show detailed error - check error code to provide helpful message
        $errorMessage = 'Failed to update profile. ';

        // Check for specific error codes
        if ($e->getCode() == 23000) { // Integrity constraint violation
            if (strpos($e->getMessage(), 'username') !== false) {
                $errorMessage .= 'Username is already taken or invalid format.';
            } elseif (strpos($e->getMessage(), 'email') !== false) {
                $errorMessage .= 'Email is already in use.';
            } else {
                $errorMessage .= 'A database constraint was violated.';
            }
        } elseif (DEBUG || defined('SHOW_ERRORS') && SHOW_ERRORS) {
            $errorMessage .= 'Error: ' . $e->getMessage() . ' (Code: ' . $e->getCode() . ')';
        } else {
            $errorMessage .= 'Please try again. If the problem persists, the username may already be taken.';
        }

        setFlash('error', $errorMessage);
        redirect('/profile.php');
    } catch (Exception $e) {
        error_log("Profile update error: " . $e->getMessage());
        if (DEBUG) {
            setFlash('error', $e->getMessage());
        } else {
            setFlash('error', 'Failed to update profile. Please try again.');
        }
        redirect('/profile.php');
    }
}

?>
<!DOCTYPE html>
<html lang="en">
<head>
    <?php partial('head', [
        'pageTitle' => 'Profile | Simple CV Builder',
        'metaDescription' => 'Manage your personal profile information.',
        'canonicalUrl' => APP_URL . '/profile.php',
        'metaNoindex' => true,
    ]); ?>
</head>
<body class="bg-gray-50">
    <?php partial('header'); ?>

    <div class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <!-- Messages -->
        <?php if ($error): ?>
            <div class="mb-6 rounded-md bg-red-50 p-4">
                <p class="text-sm font-medium text-red-800"><?php echo e($error); ?></p>
            </div>
        <?php endif; ?>

        <?php if ($success): ?>
            <div class="mb-6 rounded-md bg-green-50 p-4">
                <p class="text-sm font-medium text-green-800"><?php echo e($success); ?></p>
            </div>
        <?php endif; ?>

        <?php if ($isAutoGeneratedUsername): ?>
            <div class="mb-6 rounded-md bg-blue-50 border border-blue-200 p-4">
                <div class="flex">
                    <div class="flex-shrink-0">
                        <svg class="h-5 w-5 text-blue-400" fill="currentColor" viewBox="0 0 20 20">
                            <path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clip-rule="evenodd"/>
                        </svg>
                    </div>
                    <div class="ml-3 flex-1">
                        <h3 class="text-sm font-medium text-blue-800">Change Your Username</h3>
                        <div class="mt-2 text-sm text-blue-700">
                            <p>Your username is currently auto-generated. Please choose a unique username that will be used in your CV link.</p>
                            <p class="mt-1">Your username must:</p>
                            <ul class="list-disc list-inside mt-1 space-y-1">
                                <li>Start with a lowercase letter or number</li>
                                <li>Contain only lowercase letters, numbers, hyphens, and underscores</li>
                                <li>Be unique (not already taken by another user)</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        <?php endif; ?>

        <!-- Profile Form -->
        <div class="bg-white shadow rounded-lg">
            <form method="POST" action="/profile.php" id="profile-form">
                <input type="hidden" name="<?php echo CSRF_TOKEN_NAME; ?>" value="<?php echo csrfToken(); ?>">

                <!-- Sticky Save Button Bar -->
                <div class="sticky top-0 z-10 bg-white border-b border-gray-200 px-6 py-4 flex justify-between items-center shadow-sm">
                    <h1 class="text-2xl font-bold text-gray-900">Personal Profile</h1>
                    <div class="flex gap-3">
                        <a href="/change-password.php" class="px-4 py-2 text-blue-600 border border-blue-200 rounded-md hover:bg-blue-50">Change Password</a>
                        <a href="/dashboard.php" class="px-4 py-2 text-gray-700 hover:text-gray-900 border border-gray-300 rounded-md hover:bg-gray-50">Cancel</a>
                        <button type="submit" class="bg-blue-600 text-white px-6 py-2 rounded-md hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2">
                            Save Profile
                        </button>
                    </div>
                </div>

                <!-- Tabs Navigation -->
                <div class="border-b border-gray-200 px-6">
                    <nav class="-mb-px flex space-x-8" aria-label="Tabs">
                        <button type="button" onclick="switchTab('main')" id="tab-main" class="tab-button py-4 px-1 border-b-2 font-medium text-sm border-blue-500 text-blue-600">
                            Main
                        </button>
                        <button type="button" onclick="switchTab('photo')" id="tab-photo" class="tab-button py-4 px-1 border-b-2 font-medium text-sm border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300">
                            Photo
                        </button>
                        <button type="button" onclick="switchTab('colors')" id="tab-colors" class="tab-button py-4 px-1 border-b-2 font-medium text-sm border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300">
                            Header Colors
                        </button>
                    </nav>
                </div>

                <!-- Tab Content -->
                <div class="p-6">
                    <!-- Main Tab -->
                    <div id="tab-content-main" class="tab-content">
                        <div class="grid grid-cols-1 gap-6 sm:grid-cols-2">
                    <div>
                        <label for="full_name" class="block text-sm font-medium text-gray-700">Full Name</label>
                        <input type="text" id="full_name" name="full_name" value="<?php echo e($profile['full_name'] ?? ''); ?>" class="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500">
                    </div>

                    <div>
                        <label for="email" class="block text-sm font-medium text-gray-700">Email</label>
                        <input type="email" id="email" value="<?php echo e($profile['email'] ?? ''); ?>" disabled class="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm bg-gray-50">
                        <p class="mt-1 text-xs text-gray-500">Email cannot be changed</p>
                    </div>

                    <div>
                        <label for="username" class="block text-sm font-medium text-gray-700">Username</label>
                        <input type="text" id="username" name="username" value="<?php echo e($profile['username'] ?? ''); ?>" pattern="[a-z0-9][a-z0-9\-_]+" class="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500" oninput="updateUsernamePreview(this.value)">
                        <p class="mt-1 text-xs text-gray-500">Lowercase letters, numbers, hyphens, and underscores only. Used in your CV link: <span class="font-mono text-blue-600">/cv/@<span id="username-preview"><?php echo e($profile['username'] ?? ''); ?></span></span></p>
                        <?php if ($isAutoGeneratedUsername): ?>
                            <p class="mt-1 text-xs text-blue-600 font-medium">⚠️ Please change this to your preferred username</p>
                        <?php endif; ?>
                    </div>

                    <div>
                        <label for="phone" class="block text-sm font-medium text-gray-700">Phone</label>
                        <input type="tel" id="phone" name="phone" value="<?php echo e($profile['phone'] ?? ''); ?>" class="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500">
                    </div>

                    <div class="sm:col-span-2">
                        <label for="location" class="block text-sm font-medium text-gray-700">Location</label>
                        <input type="text" id="location" name="location" value="<?php echo e($profile['location'] ?? ''); ?>" class="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500">
                    </div>

                    <div class="sm:col-span-2">
                        <label for="linkedin_url" class="block text-sm font-medium text-gray-700">LinkedIn URL</label>
                        <input type="url" id="linkedin_url" name="linkedin_url" value="<?php echo e($profile['linkedin_url'] ?? ''); ?>" class="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500">
                    </div>

                    <div class="sm:col-span-2">
                        <label for="bio" class="block text-sm font-medium text-gray-700">Strapline</label>
                        <textarea id="bio" name="bio" rows="4" class="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500"><?php echo e($profile['bio'] ?? ''); ?></textarea>
                        <p class="mt-1 text-xs text-gray-500">A single line of text that appears on your CV</p>
                    </div>
                        </div>
                    </div>

                    <!-- Photo Tab -->
                    <div id="tab-content-photo" class="tab-content hidden">
                        <h2 class="text-xl font-semibold text-gray-900 mb-4">Profile Photo</h2>

                    <div class="flex items-start gap-6">
                        <div class="flex-shrink-0">
                            <?php if (!empty($profile['photo_url'])): ?>
                                <img id="photo-preview" src="<?php echo e($profile['photo_url']); ?>" alt="Profile Photo" class="w-32 h-32 rounded-full object-cover border-4 border-gray-200">
                            <?php else: ?>
                                <div id="photo-preview" class="w-32 h-32 rounded-full bg-gray-200 border-4 border-gray-200 flex items-center justify-center">
                                    <svg class="w-16 h-16 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z"></path>
                                    </svg>
                                </div>
                            <?php endif; ?>
                        </div>

                        <div class="flex-1">
                            <div class="flex gap-3 flex-wrap">
                                <label class="cursor-pointer bg-blue-600 text-white px-4 py-2 rounded-md hover:bg-blue-700 inline-flex items-center gap-2">
                                    <input type="file" id="photo-input" accept="image/*" capture="user" class="hidden" onchange="handlePhotoUpload(event)">
                                    <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 9a2 2 0 012-2h.93a2 2 0 001.664-.89l.812-1.22A2 2 0 0110.07 4h3.86a2 2 0 011.664.89l.812 1.22A2 2 0 0018.07 7H19a2 2 0 012 2v9a2 2 0 01-2 2H5a2 2 0 01-2-2V9z"></path>
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 13a3 3 0 11-6 0 3 3 0 016 0z"></path>
                                    </svg>
                                    <span>Take Photo</span>
                                </label>
                                <label class="cursor-pointer bg-gray-600 text-white px-4 py-2 rounded-md hover:bg-gray-700 inline-flex items-center gap-2">
                                    <input type="file" id="photo-upload" accept="image/*" class="hidden" onchange="handlePhotoUpload(event)">
                                    <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 16a4 4 0 01-.88-7.903A5 5 0 1115.9 6L16 6a5 5 0 011 9.9M15 13l-3-3m0 0l-3 3m3-3v12"></path>
                                    </svg>
                                    <span>Upload Photo</span>
                                </label>
                                <?php if (!empty($profile['photo_url'])): ?>
                                    <button type="button" onclick="deletePhoto()" class="bg-red-600 text-white px-4 py-2 rounded-md hover:bg-red-700 inline-flex items-center gap-2">
                                        <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"></path>
                                        </svg>
                                        <span>Delete Photo</span>
                                    </button>
                                <?php endif; ?>
                            </div>

                            <?php if (!empty($profile['photo_url'])): ?>
                                <?php
                                $showPhotoCv = isset($profile['show_photo']) ? (int)$profile['show_photo'] : 1;
                                $showPhotoPdf = isset($profile['show_photo_pdf']) ? (int)$profile['show_photo_pdf'] : 1;
                                ?>
                                <div class="mt-4 space-y-4">
                                    <div class="flex items-center gap-2 cursor-pointer">
                                        <input type="checkbox"
                                               id="show_photo_cv"
                                               name="show_photo_cv"
                                               value="1"
                                               <?php echo $showPhotoCv ? 'checked' : ''; ?>
                                               class="w-4 h-4 text-blue-600 border-gray-300 rounded focus:ring-blue-500">
                                        <span class="text-sm text-gray-700">Show photo on online CV</span>
                                    </div>
                                    <p class="text-xs text-gray-500">
                                        Controls the photo on your public CV page (for example <span class="font-mono text-blue-600">/cv/@<?php echo e($profile['username'] ?? 'username'); ?></span>).
                                        If you hide the photo here, a QR code linking to your CV will be displayed instead.
                                    </p>

                                    <div class="flex items-center gap-2 cursor-pointer">
                                        <input type="checkbox"
                                               id="show_photo_pdf"
                                               name="show_photo_pdf"
                                               value="1"
                                               <?php echo $showPhotoPdf ? 'checked' : ''; ?>
                                               class="w-4 h-4 text-blue-600 border-gray-300 rounded focus:ring-blue-500">
                                        <span class="text-sm text-gray-700">Show photo by default in PDF</span>
                                    </div>
                                    <p class="text-xs text-gray-500">
                                        Sets the default for the PDF preview. You can still toggle the photo on or off while generating the PDF.
                                    </p>
                                </div>
                            <?php endif; ?>

                            <p class="mt-2 text-sm text-gray-500">Upload a professional photo. Supported formats: JPG, PNG, GIF, WebP (max 5MB)</p>
                            <div id="photo-upload-status" class="mt-2"></div>
                        </div>
                    </div>
                    </div>

                    <!-- Header Colors Tab -->
                    <div id="tab-content-colors" class="tab-content hidden">
                        <h2 class="text-xl font-semibold text-gray-900 mb-4">CV Header Colors</h2>

                    <!-- Predefined Color Schemes -->
                    <div class="mb-6">
                        <label class="block text-sm font-medium text-gray-700 mb-3">Choose a Color Scheme</label>
                        <div class="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-3">
                            <?php
                            $colorSchemes = [
                                ['name' => 'Indigo to Purple', 'from' => '#4338ca', 'to' => '#7e22ce'],
                                ['name' => 'Blue to Cyan', 'from' => '#2563eb', 'to' => '#06b6d4'],
                                ['name' => 'Green to Teal', 'from' => '#059669', 'to' => '#14b8a6'],
                                ['name' => 'Red to Pink', 'from' => '#dc2626', 'to' => '#ec4899'],
                                ['name' => 'Orange to Red', 'from' => '#ea580c', 'to' => '#dc2626'],
                                ['name' => 'Purple to Pink', 'from' => '#7c3aed', 'to' => '#ec4899'],
                                ['name' => 'Slate to Blue', 'from' => '#475569', 'to' => '#3b82f6'],
                                ['name' => 'Emerald to Blue', 'from' => '#10b981', 'to' => '#3b82f6'],
                            ];

                            $currentFrom = $profile['cv_header_from_color'] ?? '#4338ca';
                            $currentTo = $profile['cv_header_to_color'] ?? '#7e22ce';

                            foreach ($colorSchemes as $scheme):
                                $isSelected = ($scheme['from'] === $currentFrom && $scheme['to'] === $currentTo);
                            ?>
                                <button type="button" onclick="selectColorScheme('<?php echo $scheme['from']; ?>', '<?php echo $scheme['to']; ?>')"
                                        class="relative p-3 border-2 rounded-lg hover:border-blue-500 transition-colors <?php echo $isSelected ? 'border-blue-600 ring-2 ring-blue-500' : 'border-gray-200'; ?>">
                                    <div class="w-full h-16 rounded mb-2" style="background: linear-gradient(to right, <?php echo $scheme['from']; ?>, <?php echo $scheme['to']; ?>);"></div>
                                    <p class="text-xs text-gray-600 text-center"><?php echo e($scheme['name']); ?></p>
                                    <?php if ($isSelected): ?>
                                        <svg class="absolute top-1 right-1 w-5 h-5 text-blue-600" fill="currentColor" viewBox="0 0 20 20">
                                            <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd"/>
                                        </svg>
                                    <?php endif; ?>
                                </button>
                            <?php endforeach; ?>
                        </div>
                    </div>

                    <!-- Custom Color Pickers -->
                    <div class="grid grid-cols-1 sm:grid-cols-2 gap-6">
                        <div>
                            <label for="cv_header_from_color" class="block text-sm font-medium text-gray-700 mb-2">Start Color</label>
                            <div class="flex gap-3">
                                <input type="color"
                                       id="cv_header_from_color"
                                       name="cv_header_from_color"
                                       value="<?php echo e($profile['cv_header_from_color'] ?? '#4338ca'); ?>"
                                       class="h-10 w-20 rounded border border-gray-300 cursor-pointer"
                                       onchange="updatePreview()">
                                <input type="text"
                                       id="cv_header_from_color_text"
                                       value="<?php echo e($profile['cv_header_from_color'] ?? '#4338ca'); ?>"
                                       pattern="^#[0-9A-Fa-f]{6}$"
                                       class="flex-1 px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500"
                                       placeholder="#4338ca"
                                       onchange="updateColorFromText('from')">
                            </div>
                        </div>
                        <div>
                            <label for="cv_header_to_color" class="block text-sm font-medium text-gray-700 mb-2">End Color</label>
                            <div class="flex gap-3">
                                <input type="color"
                                       id="cv_header_to_color"
                                       name="cv_header_to_color"
                                       value="<?php echo e($profile['cv_header_to_color'] ?? '#7e22ce'); ?>"
                                       class="h-10 w-20 rounded border border-gray-300 cursor-pointer"
                                       onchange="updatePreview()">
                                <input type="text"
                                       id="cv_header_to_color_text"
                                       value="<?php echo e($profile['cv_header_to_color'] ?? '#7e22ce'); ?>"
                                       pattern="^#[0-9A-Fa-f]{6}$"
                                       class="flex-1 px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500"
                                       placeholder="#7e22ce"
                                       onchange="updateColorFromText('to')">
                            </div>
                        </div>
                    </div>

                    <!-- Preview -->
                    <div class="mt-4">
                        <label class="block text-sm font-medium text-gray-700 mb-2">Preview</label>
                        <div id="color-preview" class="w-full h-24 rounded-lg shadow-sm" style="background: linear-gradient(to right, <?php echo e($profile['cv_header_from_color'] ?? '#4338ca'); ?>, <?php echo e($profile['cv_header_to_color'] ?? '#7e22ce'); ?>);"></div>
                    </div>
                    </div>
                </div>
            </form>
        </div>
    </div>

    <script>
        // Tab switching functionality
        function switchTab(tabName) {
            // Hide all tab contents
            document.querySelectorAll('.tab-content').forEach(content => {
                content.classList.add('hidden');
            });

            // Remove active styling from all tabs
            document.querySelectorAll('.tab-button').forEach(button => {
                button.classList.remove('border-blue-500', 'text-blue-600');
                button.classList.add('border-transparent', 'text-gray-500');
            });

            // Show selected tab content
            const selectedContent = document.getElementById('tab-content-' + tabName);
            if (selectedContent) {
                selectedContent.classList.remove('hidden');
            }

            // Add active styling to selected tab
            const selectedTab = document.getElementById('tab-' + tabName);
            if (selectedTab) {
                selectedTab.classList.remove('border-transparent', 'text-gray-500');
                selectedTab.classList.add('border-blue-500', 'text-blue-600');
            }
        }

        // Initialize - show main tab by default
        document.addEventListener('DOMContentLoaded', function() {
            switchTab('main');
        });

        function selectColorScheme(fromColor, toColor) {
            document.getElementById('cv_header_from_color').value = fromColor;
            document.getElementById('cv_header_from_color_text').value = fromColor;
            document.getElementById('cv_header_to_color').value = toColor;
            document.getElementById('cv_header_to_color_text').value = toColor;
            updatePreview();
        }

        function updateColorFromText(type) {
            const textInput = type === 'from' ? document.getElementById('cv_header_from_color_text') : document.getElementById('cv_header_to_color_text');
            const colorInput = type === 'from' ? document.getElementById('cv_header_from_color') : document.getElementById('cv_header_to_color');
            const value = textInput.value.trim();

            if (/^#[0-9A-Fa-f]{6}$/.test(value)) {
                colorInput.value = value;
                updatePreview();
            }
        }

        function updatePreview() {
            const fromColor = document.getElementById('cv_header_from_color').value;
            const toColor = document.getElementById('cv_header_to_color').value;
            const preview = document.getElementById('color-preview');
            if (preview) {
                preview.style.background = `linear-gradient(to right, ${fromColor}, ${toColor})`;
            }

            // Update text inputs to match color picker
            const fromText = document.getElementById('cv_header_from_color_text');
            const toText = document.getElementById('cv_header_to_color_text');
            if (fromText) fromText.value = fromColor;
            if (toText) toText.value = toColor;
        }

        // Initialize event listeners when page loads
        document.addEventListener('DOMContentLoaded', function() {
            const fromColorPicker = document.getElementById('cv_header_from_color');
            const toColorPicker = document.getElementById('cv_header_to_color');

            if (fromColorPicker) {
                fromColorPicker.addEventListener('input', updatePreview);
            }
            if (toColorPicker) {
                toColorPicker.addEventListener('input', updatePreview);
            }
        });

        function handlePhotoUpload(event) {
            const file = event.target.files[0];
            if (!file) return;

            // Validate file size (5MB)
            if (file.size > 5 * 1024 * 1024) {
                showStatus('File too large. Maximum size is 5MB.', 'error');
                return;
            }

            // Validate file type
            if (!file.type.match('image.*')) {
                showStatus('Please select an image file.', 'error');
                return;
            }

            // Show preview
            const reader = new FileReader();
            reader.onload = function(e) {
                const preview = document.getElementById('photo-preview');
                if (preview.tagName === 'IMG') {
                    preview.src = e.target.result;
                } else {
                    // Replace div with img
                    const img = document.createElement('img');
                    img.id = 'photo-preview';
                    img.src = e.target.result;
                    img.alt = 'Profile Photo';
                    img.className = 'w-32 h-32 rounded-full object-cover border-4 border-gray-200';
                    preview.parentNode.replaceChild(img, preview);
                }
            };
            reader.readAsDataURL(file);

            // Upload file
            const formData = new FormData();
            formData.append('photo', file);
            formData.append('<?php echo CSRF_TOKEN_NAME; ?>', '<?php echo csrfToken(); ?>');

            showStatus('Uploading...', 'info');

            fetch('/api/update-profile-photo.php', {
                method: 'POST',
                body: formData
            })
            .then(response => response.json())
            .then(data => {
                if (data.success) {
                    showStatus('Photo uploaded successfully!', 'success');
                    // Update preview with server URL
                    document.getElementById('photo-preview').src = data.url + '?t=' + Date.now();
                } else {
                    showStatus('Error: ' + (data.error || 'Upload failed'), 'error');
                }
            })
            .catch(error => {
                showStatus('Error uploading photo: ' + error.message, 'error');
            });
        }

        function deletePhoto() {
            if (!confirm('Are you sure you want to delete your profile photo?')) {
                return;
            }

            const formData = new FormData();
            formData.append('action', 'delete');
            formData.append('<?php echo CSRF_TOKEN_NAME; ?>', '<?php echo csrfToken(); ?>');

            fetch('/api/update-profile-photo.php', {
                method: 'POST',
                body: formData
            })
            .then(response => response.json())
            .then(data => {
                if (data.success) {
                    // Replace img with placeholder div
                    const preview = document.getElementById('photo-preview');
                    const div = document.createElement('div');
                    div.id = 'photo-preview';
                    div.className = 'w-32 h-32 rounded-full bg-gray-200 border-4 border-gray-200 flex items-center justify-center';
                    div.innerHTML = '<svg class="w-16 h-16 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z"></path></svg>';
                    preview.parentNode.replaceChild(div, preview);
                    showStatus('Photo deleted successfully!', 'success');
                } else {
                    showStatus('Error: ' + (data.error || 'Delete failed'), 'error');
                }
            })
            .catch(error => {
                showStatus('Error deleting photo: ' + error.message, 'error');
            });
        }

        function showStatus(message, type) {
            const statusDiv = document.getElementById('photo-upload-status');
            const colors = {
                success: 'text-green-600 bg-green-50',
                error: 'text-red-600 bg-red-50',
                info: 'text-blue-600 bg-blue-50'
            };
            statusDiv.innerHTML = `<p class="text-sm p-2 rounded ${colors[type] || colors.info}">${message}</p>`;
            setTimeout(() => {
                statusDiv.innerHTML = '';
            }, 5000);
        }

        function updateUsernamePreview(value) {
            const preview = document.getElementById('username-preview');
            if (preview) {
                preview.textContent = value || 'yourname';
            }
        }
    </script>

    <?php partial('footer'); ?>
</body>
</html>
