<?php
/**
 * Account page - username, password, and job-reminder preferences.
 * Name/contact/photo, header colours, accent colour, and CV visibility are edited
 * in the content editor (Profile / Appearance / Visibility sections).
 */

require_once __DIR__ . '/php/helpers.php';

requireAuth();

$userId = getUserId();
$error = getFlash('error');
$success = getFlash('success');
$passwordError = getFlash('password_error');
$passwordSuccess = getFlash('password_success');

// Get profile data
$profile = db()->fetchOne(
    "SELECT * FROM profiles WHERE id = ?",
    [$userId]
);

// Check if username is auto-generated (starts with "user" followed by 8 alphanumeric chars)
$isAutoGeneratedUsername = preg_match('/^user[a-z0-9]{8}$/i', $profile['username'] ?? '');

// Subscription summary (read-only here; upgrade/cancel/billing all happen on /subscription.php)
$subscriptionContext = getUserSubscriptionContext($userId);
$expiryInfo = formatSubscriptionExpiry($subscriptionContext);

// Handle form submission
if (isPost()) {
    // Password change (separate from main account form)
    if (post('profile_action') === 'change_password') {
        if (!verifyCsrfToken(post(CSRF_TOKEN_NAME))) {
            setFlash('password_error', 'Invalid security token. Please try again.');
            redirect('/profile.php?tab=password');
        }
        $currentPassword = post('current_password', '');
        $newPassword = post('new_password', '');
        $confirmPassword = post('confirm_password', '');
        if ($newPassword !== $confirmPassword) {
            setFlash('password_error', 'New passwords do not match.');
            redirect('/profile.php?tab=password');
        }
        $result = changePasswordForUser($userId, $currentPassword, $newPassword);
        if ($result['success']) {
            setFlash('password_success', 'Your password has been updated successfully.');
            redirect('/profile.php?tab=password');
        }
        setFlash('password_error', $result['error']);
        redirect('/profile.php?tab=password');
    }

    // Verify CSRF token (main account form)
    $token = post(CSRF_TOKEN_NAME);
    if (!verifyCsrfToken($token)) {
        setFlash('error', 'Invalid security token. Please try again.');
        redirect('/profile.php');
    }

    $data = [];

    // Username is required, so we must have it
    $username = trim(post('username', ''));
    if ($username === '') {
        setFlash('error', 'Username is required');
        redirect('/profile.php');
    }
    $data['username'] = strip_tags($username);

    if (!preg_match('/^[a-z0-9][a-z0-9\-_]+$/', $data['username'])) {
        setFlash('error', 'Username can only contain lowercase letters, numbers, hyphens, and underscores');
        redirect('/profile.php');
    }

    // Check if username is already taken by another user
    $existing = db()->fetchOne(
        "SELECT id FROM profiles WHERE username = ? AND id != ?",
        [$data['username'], $userId]
    );

    if ($existing) {
        setFlash('error', 'Username is already taken');
        redirect('/profile.php');
    }

    if (checkForXss($data['username'])) {
        setFlash('error', 'Invalid content in username');
        redirect('/profile.php');
    }

    // Closing date reminder preferences (only if migration has run)
    if (array_key_exists('closing_date_reminder_enabled', $profile)) {
        $data['closing_date_reminder_enabled'] = (post('closing_date_reminder_enabled') === '1' || post('closing_date_reminder_enabled') === 'on') ? 1 : 0;
        $customDays = array_filter(array_map('intval', preg_split('/[\s,]+/', trim(post('closing_date_reminder_days_custom', '')), -1, PREG_SPLIT_NO_EMPTY)));
        $presetDays = [];
        if (post('remind_14') === '1' || post('remind_14') === 'on') $presetDays[] = 14;
        if (post('remind_7') === '1' || post('remind_7') === 'on') $presetDays[] = 7;
        if (post('remind_3') === '1' || post('remind_3') === 'on') $presetDays[] = 3;
        if (post('remind_1') === '1' || post('remind_1') === 'on') $presetDays[] = 1;
        $allDays = array_unique(array_merge($presetDays, $customDays));
        sort($allDays, SORT_NUMERIC);
        $data['closing_date_reminder_days'] = implode(',', $allDays) ?: '7,3,1';
    }

    $data['updated_at'] = date('Y-m-d H:i:s');

    // Update profile
    try {
        db()->update('profiles', $data, 'id = ?', [$userId]);
        setFlash('success', 'Account updated successfully');
        redirect('/profile.php');
    } catch (PDOException $e) {
        error_log("Profile update error: " . $e->getMessage());
        error_log("SQL State: " . $e->getCode());
        error_log("User ID: " . $userId);
        error_log("Data being updated: " . print_r($data, true));

        $errorMessage = 'Failed to update account. ';

        if ($e->getCode() == 23000) { // Integrity constraint violation
            if (strpos($e->getMessage(), 'username') !== false) {
                $errorMessage .= 'Username is already taken or invalid format.';
            } else {
                $errorMessage .= 'A database constraint was violated.';
            }
        } elseif (DEBUG || defined('SHOW_ERRORS') && SHOW_ERRORS) {
            $errorMessage .= 'Error: ' . $e->getMessage() . ' (Code: ' . $e->getCode() . ')';
        } else {
            $errorMessage .= 'Please try again. If the problem persists, the username may already be taken.';
        }

        setFlash('error', $errorMessage);
        redirect('/profile.php');
    } catch (Exception $e) {
        error_log("Profile update error: " . $e->getMessage());
        if (DEBUG) {
            setFlash('error', $e->getMessage());
        } else {
            setFlash('error', 'Failed to update account. Please try again.');
        }
        redirect('/profile.php');
    }
}

?>
<!DOCTYPE html>
<html lang="en">
<head>
    <?php partial('head', [
        'pageTitle' => 'Account | Simple CV Builder',
        'metaDescription' => 'Manage your account settings.',
        'canonicalUrl' => APP_URL . '/profile.php',
        'metaNoindex' => true,
    ]); ?>
</head>
<body class="bg-gray-50">
    <?php partial('header'); ?>

    <div class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <!-- Messages -->
        <?php if ($error): ?>
            <div class="mb-6 rounded-md bg-red-50 p-4">
                <p class="text-sm font-medium text-red-800"><?php echo e($error); ?></p>
            </div>
        <?php endif; ?>

        <?php if ($success): ?>
            <div class="mb-6 rounded-md bg-green-50 p-4">
                <p class="text-sm font-medium text-green-800"><?php echo e($success); ?></p>
            </div>
        <?php endif; ?>

        <?php if ($isAutoGeneratedUsername): ?>
            <div class="mb-6 rounded-md bg-blue-50 border border-blue-200 p-4">
                <div class="flex">
                    <div class="flex-shrink-0">
                        <svg class="h-5 w-5 text-blue-400" fill="currentColor" viewBox="0 0 20 20">
                            <path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clip-rule="evenodd"/>
                        </svg>
                    </div>
                    <div class="ml-3 flex-1">
                        <h3 class="text-sm font-medium text-blue-800">Change Your Username</h3>
                        <div class="mt-2 text-sm text-blue-700">
                            <p>Your username is currently auto-generated. Please choose a unique username that will be used in your CV link.</p>
                            <p class="mt-1">Your username must:</p>
                            <ul class="list-disc list-inside mt-1 space-y-1">
                                <li>Start with a lowercase letter or number</li>
                                <li>Contain only lowercase letters, numbers, hyphens, and underscores</li>
                                <li>Be unique (not already taken by another user)</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        <?php endif; ?>

        <!-- Account Form -->
        <div class="bg-white shadow rounded-lg">
            <form method="POST" action="/profile.php" id="profile-form">
                <input type="hidden" name="<?php echo CSRF_TOKEN_NAME; ?>" value="<?php echo csrfToken(); ?>">

                <!-- Sticky Save Button Bar -->
                <div class="sticky top-0 z-10 bg-white border-b border-gray-200 px-6 py-4 flex flex-wrap justify-between items-center gap-3 shadow-sm">
                    <h1 class="text-2xl font-bold text-gray-900">Account</h1>
                    <div class="flex flex-wrap gap-3">
                        <a href="/content-editor.php" class="inline-flex items-center gap-2 px-4 py-2 bg-green-600 text-white rounded-md hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-green-500 focus:ring-offset-2 font-medium">
                            <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z"/></svg>
                            Edit My CV
                        </a>
                        <a href="/dashboard.php" class="px-4 py-2 text-gray-700 hover:text-gray-900 border border-gray-300 rounded-md hover:bg-gray-50">Cancel</a>
                        <button type="submit" class="bg-blue-600 text-white px-6 py-2 rounded-md hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2">
                            Save
                        </button>
                    </div>
                </div>

                <!-- Tabs Navigation -->
                <div class="px-6 py-3 bg-gray-100 border-b border-gray-200">
                    <nav class="flex flex-nowrap gap-2 overflow-x-auto pb-1" aria-label="Account tabs">
                        <button type="button" onclick="switchTab('main')" id="tab-main" class="tab-button shrink-0 py-2.5 px-4 rounded-lg font-medium text-sm border-2 border-blue-500 bg-blue-50 text-blue-700 whitespace-nowrap flex items-center gap-1.5 shadow-sm">
                            <span>Details</span>
                        </button>
                        <button type="button" onclick="switchTab('subscription')" id="tab-subscription" class="tab-button shrink-0 py-2.5 px-4 rounded-lg font-medium text-sm border-2 border-gray-200 bg-white text-gray-600 hover:border-gray-300 hover:bg-gray-50 whitespace-nowrap flex items-center gap-1.5 shadow-sm">
                            <span>Subscription</span>
                        </button>
                        <button type="button" onclick="switchTab('ai')" id="tab-ai" class="tab-button shrink-0 py-2.5 px-4 rounded-lg font-medium text-sm border-2 border-gray-200 bg-white text-gray-600 hover:border-gray-300 hover:bg-gray-50 whitespace-nowrap flex items-center gap-1.5 shadow-sm">
                            <span>AI Settings</span>
                        </button>
                        <?php if (array_key_exists('closing_date_reminder_enabled', $profile)): ?>
                        <button type="button" onclick="switchTab('reminders')" id="tab-reminders" class="tab-button shrink-0 py-2.5 px-4 rounded-lg font-medium text-sm border-2 border-gray-200 bg-white text-gray-600 hover:border-gray-300 hover:bg-gray-50 whitespace-nowrap flex items-center gap-1.5 shadow-sm">
                            <span>Reminders</span>
                        </button>
                        <?php endif; ?>
                        <button type="button" onclick="switchTab('password')" id="tab-password" class="tab-button shrink-0 py-2.5 px-4 rounded-lg font-medium text-sm border-2 border-gray-200 bg-white text-gray-600 hover:border-gray-300 hover:bg-gray-50 whitespace-nowrap flex items-center gap-1.5 shadow-sm">
                            <span>Password</span>
                        </button>
                        <button type="button" onclick="switchTab('danger')" id="tab-danger" class="tab-button shrink-0 py-2.5 px-4 rounded-lg font-medium text-sm border-2 border-gray-200 bg-white text-gray-600 hover:border-gray-300 hover:bg-gray-50 whitespace-nowrap flex items-center gap-1.5 shadow-sm">
                            <span>Danger Zone</span>
                        </button>
                    </nav>
                </div>

                <!-- Tab Content -->
                <div class="p-6">
                    <!-- Main (Details) Tab -->
                    <div id="tab-content-main" class="tab-content">
                        <div class="grid grid-cols-1 gap-6 sm:grid-cols-2">
                            <div>
                                <label for="email" class="block text-sm font-medium text-gray-700">Email</label>
                                <input type="email" id="email" value="<?php echo e($profile['email'] ?? ''); ?>" disabled class="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm bg-gray-50">
                                <p class="mt-1 text-xs text-gray-500">Email cannot be changed</p>
                            </div>

                            <div>
                                <label for="username" class="block text-sm font-medium text-gray-700">Username</label>
                                <input type="text" id="username" name="username" value="<?php echo e($profile['username'] ?? ''); ?>" pattern="[a-z0-9][a-z0-9\-_]+" class="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500" oninput="updateUsernamePreview(this.value)">
                                <p class="mt-1 text-xs text-gray-500">Lowercase letters, numbers, hyphens, and underscores only.</p>
                                <p class="mt-1 text-xs text-gray-500">
                                    Your CV link:
                                    <a href="<?php echo e(APP_URL . '/cv/@' . ($profile['username'] ?? '')); ?>" target="_blank" rel="noopener" class="font-mono hover:underline">
                                        <span class="text-gray-500"><?php echo e(APP_URL); ?></span><span class="text-blue-600 font-semibold">/cv/@<span id="username-preview"><?php echo e($profile['username'] ?? ''); ?></span></span>
                                    </a>
                                </p>
                                <?php if ($isAutoGeneratedUsername): ?>
                                    <p class="mt-1 text-xs text-blue-600 font-medium flex items-center gap-1.5"><svg class="w-4 h-4 flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24" aria-hidden="true"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z"/></svg>Please change this to your preferred username</p>
                                <?php endif; ?>
                            </div>
                        </div>
                    </div>

                    <!-- Subscription tab (read-only summary; upgrade/cancel/billing on /subscription.php) -->
                    <div id="tab-content-subscription" class="tab-content hidden">
                        <?php
                        $subStatusColor = $expiryInfo['status_color'];
                        $subColorClasses = [
                            'red' => ['border-red-300 bg-red-50', 'text-red-900', 'text-red-800', 'text-red-700 hover:text-red-900'],
                            'yellow' => ['border-yellow-300 bg-yellow-50', 'text-yellow-900', 'text-yellow-800', 'text-yellow-700 hover:text-yellow-900'],
                        ];
                        [$subCardClass, $subHeadingClass, $subBodyClass, $subLinkClass] = $subColorClasses[$subStatusColor] ?? ['border-blue-200 bg-blue-50', 'text-blue-900', 'text-blue-800', 'text-blue-700 hover:text-blue-900'];
                        ?>
                        <div class="rounded-lg border <?php echo $subCardClass; ?> p-4">
                            <div class="flex items-center justify-between flex-wrap gap-3">
                                <div>
                                    <h2 class="text-sm font-semibold <?php echo $subHeadingClass; ?> mb-1">
                                        Plan: <?php echo e(subscriptionPlanLabel($subscriptionContext)); ?>
                                    </h2>
                                    <p class="text-sm <?php echo $subBodyClass; ?>">
                                        <?php if ($expiryInfo['days_remaining'] !== null): ?>
                                            <?php echo e($expiryInfo['status_text']); ?> — Expires <?php echo e($expiryInfo['formatted_date']); ?>
                                        <?php else: ?>
                                            <?php echo e($expiryInfo['status_text']); ?>
                                        <?php endif; ?>
                                    </p>
                                </div>
                                <a href="/subscription.php" class="text-sm font-medium <?php echo $subLinkClass; ?> underline whitespace-nowrap">
                                    Manage subscription &amp; billing &rarr;
                                </a>
                            </div>
                        </div>
                    </div>

                    <!-- AI Settings tab (read-only summary; full configuration on /ai-settings.php) -->
                    <div id="tab-content-ai" class="tab-content hidden">
                        <?php
                        $aiServiceLabels = [
                            'openai' => 'OpenAI',
                            'anthropic' => 'Anthropic Claude',
                            'gemini' => 'Google Gemini',
                            'grok' => 'xAI Grok',
                            'ollama' => 'Local Ollama',
                            'browser' => 'Browser-Based AI',
                        ];
                        $aiServicePref = $profile['ai_service_preference'] ?? 'browser';
                        $aiServiceLabel = $aiServiceLabels[$aiServicePref] ?? $aiServicePref;
                        ?>
                        <div class="rounded-lg border border-blue-200 bg-blue-50 p-4">
                            <div class="flex items-center justify-between flex-wrap gap-3">
                                <div>
                                    <h2 class="text-sm font-semibold text-blue-900 mb-1">AI Provider: <?php echo e($aiServiceLabel); ?></h2>
                                    <?php if ($aiServicePref === 'browser' && !empty($profile['browser_ai_model'])): ?>
                                        <p class="text-sm text-blue-800">Model: <?php echo e($profile['browser_ai_model']); ?></p>
                                    <?php elseif ($aiServicePref === 'ollama' && !empty($profile['ollama_model'])): ?>
                                        <p class="text-sm text-blue-800">Model: <?php echo e($profile['ollama_model']); ?></p>
                                    <?php endif; ?>
                                </div>
                                <a href="/ai-settings.php" class="text-sm font-medium text-blue-700 hover:text-blue-900 underline whitespace-nowrap">
                                    Manage AI settings &rarr;
                                </a>
                            </div>
                        </div>
                    </div>

                    <?php if (array_key_exists('closing_date_reminder_enabled', $profile)): ?>
                    <!-- Job closing date reminders tab -->
                    <div id="tab-content-reminders" class="tab-content hidden">
                        <h2 class="text-xl font-semibold text-gray-900 mb-4">Job application closing date reminders</h2>
                        <p class="text-sm text-gray-600 mb-6">Get browser notifications when a closing date is approaching for jobs you haven’t applied to yet (status <strong>Interested</strong> or <strong>In Progress</strong>).</p>
                        <div class="space-y-4">
                            <label class="flex items-start gap-3 cursor-pointer">
                                <input type="checkbox" name="closing_date_reminder_enabled" value="1"
                                    <?php echo !empty($profile['closing_date_reminder_enabled']) ? 'checked' : ''; ?>
                                    class="mt-1 h-4 w-4 rounded border-gray-300 text-blue-600 focus:ring-blue-500">
                                <span class="text-sm font-medium text-gray-700">Enable closing date reminders (browser notifications)</span>
                            </label>
                            <div>
                                <p class="text-sm font-medium text-gray-700 mb-2">Notify me this many days before the closing date:</p>
                                <div class="flex flex-wrap gap-4 mb-2">
                                    <?php
                                    $savedDays = isset($profile['closing_date_reminder_days']) ? array_map('intval', array_filter(explode(',', $profile['closing_date_reminder_days']))) : [7, 3, 1];
                                    ?>
                                    <label class="inline-flex items-center gap-2"><input type="checkbox" name="remind_14" value="1" <?php echo in_array(14, $savedDays) ? 'checked' : ''; ?> class="rounded border-gray-300 text-blue-600 focus:ring-blue-500"> 14 days</label>
                                    <label class="inline-flex items-center gap-2"><input type="checkbox" name="remind_7" value="1" <?php echo in_array(7, $savedDays) ? 'checked' : ''; ?> class="rounded border-gray-300 text-blue-600 focus:ring-blue-500"> 7 days</label>
                                    <label class="inline-flex items-center gap-2"><input type="checkbox" name="remind_3" value="1" <?php echo in_array(3, $savedDays) ? 'checked' : ''; ?> class="rounded border-gray-300 text-blue-600 focus:ring-blue-500"> 3 days</label>
                                    <label class="inline-flex items-center gap-2"><input type="checkbox" name="remind_1" value="1" <?php echo in_array(1, $savedDays) ? 'checked' : ''; ?> class="rounded border-gray-300 text-blue-600 focus:ring-blue-500"> 1 day</label>
                                </div>
                                <p class="text-xs text-gray-500 mt-1">Or add custom days (comma-separated, e.g. 14, 5, 2):</p>
                                <input type="text" name="closing_date_reminder_days_custom" placeholder="e.g. 14, 5, 2"
                                    value="<?php echo e(implode(', ', array_diff($savedDays, [14, 7, 3, 1]))); ?>"
                                    class="mt-1 block w-full max-w-xs px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:ring-blue-500 focus:border-blue-500 text-sm">
                            </div>
                        </div>
                    </div>
                    <?php endif; ?>
            </form>

                    <!-- Password tab (own form; not nested) -->
                    <div id="tab-content-password" class="tab-content hidden">
                        <h2 class="text-xl font-semibold text-gray-900 mb-4">Change password</h2>
                        <p class="text-sm text-gray-600 mb-6">Update your account password. Use at least 8 characters with uppercase, lowercase, and a number.</p>
                        <?php if ($passwordError): ?>
                            <div class="mb-4 rounded-md bg-red-50 border border-red-200 p-4 text-sm text-red-700"><?php echo e($passwordError); ?></div>
                        <?php endif; ?>
                        <?php if ($passwordSuccess): ?>
                            <div class="mb-4 rounded-md bg-green-50 border border-green-200 p-4 text-sm text-green-700"><?php echo e($passwordSuccess); ?></div>
                        <?php endif; ?>
                        <form method="POST" action="/profile.php" class="space-y-4 max-w-md">
                            <input type="hidden" name="<?php echo CSRF_TOKEN_NAME; ?>" value="<?php echo csrfToken(); ?>">
                            <input type="hidden" name="profile_action" value="change_password">
                            <div>
                                <label for="current_password" class="block text-sm font-medium text-gray-700 mb-1">Current password</label>
                                <input type="password" id="current_password" name="current_password" required
                                    class="w-full rounded-md border border-gray-300 px-3 py-2 shadow-sm focus:border-blue-500 focus:ring-blue-500">
                            </div>
                            <div>
                                <label for="new_password" class="block text-sm font-medium text-gray-700 mb-1">New password</label>
                                <input type="password" id="new_password" name="new_password" required minlength="8"
                                    class="w-full rounded-md border border-gray-300 px-3 py-2 shadow-sm focus:border-blue-500 focus:ring-blue-500">
                            </div>
                            <div>
                                <label for="confirm_password" class="block text-sm font-medium text-gray-700 mb-1">Confirm new password</label>
                                <input type="password" id="confirm_password" name="confirm_password" required minlength="8"
                                    class="w-full rounded-md border border-gray-300 px-3 py-2 shadow-sm focus:border-blue-500 focus:ring-blue-500">
                            </div>
                            <button type="submit" class="inline-flex items-center rounded-md bg-blue-600 px-4 py-2 text-sm font-medium text-white hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2">
                                Update password
                            </button>
                        </form>
                    </div>

                    <!-- Danger Zone tab -->
                    <div id="tab-content-danger" class="tab-content hidden space-y-6">
                        <div>
                            <h2 class="text-xl font-semibold text-gray-900 mb-2">Export your data</h2>
                            <p class="text-sm text-gray-600 mb-4">Download everything you've stored with us - CV content, job applications, cover letters, and CV variants - as a JSON file.</p>
                            <a href="/api/account/export-data.php" class="inline-flex items-center gap-2 px-4 py-2 border border-gray-300 rounded-md text-sm font-medium text-gray-700 hover:bg-gray-50">
                                <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4"/></svg>
                                Download my data
                            </a>
                        </div>

                        <div class="border-t border-gray-200 pt-6">
                            <h2 class="text-xl font-semibold text-red-700 mb-2">Delete your account</h2>
                            <p class="text-sm text-gray-600 mb-4">This permanently deletes your profile, CV content, job applications, cover letters, and CV variants. This cannot be undone. If you have an active paid subscription, it will be cancelled automatically.</p>
                            <button type="button" id="open-delete-account-modal" class="inline-flex items-center gap-2 px-4 py-2 bg-red-600 text-white rounded-md text-sm font-medium hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-red-500 focus:ring-offset-2">
                                Delete my account
                            </button>
                        </div>
                    </div>

                </div>
        </div>

        <!-- Delete account confirmation modal -->
        <div id="delete-account-modal" class="fixed inset-0 z-50 hidden items-center justify-center bg-black/50 p-4">
            <div class="bg-white rounded-lg shadow-xl max-w-md w-full p-6">
                <h3 class="text-lg font-semibold text-gray-900 mb-2">Delete your account?</h3>
                <p class="text-sm text-gray-600 mb-4">This is permanent and cannot be undone. Enter your password and type <strong>DELETE</strong> to confirm.</p>
                <div id="delete-account-error" class="hidden mb-4 rounded-md bg-red-50 border border-red-200 p-3 text-sm text-red-700"></div>
                <div class="space-y-4">
                    <div>
                        <label for="delete-account-password" class="block text-sm font-medium text-gray-700 mb-1">Password</label>
                        <input type="password" id="delete-account-password" class="w-full rounded-md border border-gray-300 px-3 py-2 shadow-sm focus:border-blue-500 focus:ring-blue-500">
                    </div>
                    <div>
                        <label for="delete-account-confirmation" class="block text-sm font-medium text-gray-700 mb-1">Type DELETE to confirm</label>
                        <input type="text" id="delete-account-confirmation" class="w-full rounded-md border border-gray-300 px-3 py-2 shadow-sm focus:border-blue-500 focus:ring-blue-500">
                    </div>
                </div>
                <div class="mt-6 flex justify-end gap-3">
                    <button type="button" id="cancel-delete-account" class="px-4 py-2 text-gray-700 hover:text-gray-900 border border-gray-300 rounded-md hover:bg-gray-50">Cancel</button>
                    <button type="button" id="confirm-delete-account" class="px-4 py-2 bg-red-600 text-white rounded-md hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-red-500 focus:ring-offset-2">Delete my account</button>
                </div>
            </div>
        </div>

        <p class="mt-4 text-center text-sm text-gray-500">
            <a href="/terms.php" class="hover:text-gray-700 hover:underline">Terms of Service</a>
            &middot;
            <a href="/privacy.php" class="hover:text-gray-700 hover:underline">Privacy Policy</a>
        </p>
    </div>

    <script>
        // Tab switching functionality
        function switchTab(tabName) {
            // Hide all tab contents
            document.querySelectorAll('.tab-content').forEach(content => {
                content.classList.add('hidden');
            });

            // Remove active styling from all tabs
            document.querySelectorAll('.tab-button').forEach(button => {
                button.classList.remove('border-blue-500', 'bg-blue-50', 'text-blue-700');
                button.classList.add('border-gray-200', 'bg-white', 'text-gray-600');
            });

            // Show selected tab content
            const selectedContent = document.getElementById('tab-content-' + tabName);
            if (selectedContent) {
                selectedContent.classList.remove('hidden');
            }

            // Add active styling to selected tab
            const selectedTab = document.getElementById('tab-' + tabName);
            if (selectedTab) {
                selectedTab.classList.remove('border-gray-200', 'bg-white', 'text-gray-600');
                selectedTab.classList.add('border-blue-500', 'bg-blue-50', 'text-blue-700');
            }
        }

        // Initialize - show main tab or ?tab= query
        document.addEventListener('DOMContentLoaded', function() {
            var match = /[?&]tab=([^&]+)/.exec(window.location.search);
            var tab = match ? match[1] : 'main';
            if (document.getElementById('tab-' + tab)) {
                switchTab(tab);
            } else {
                switchTab('main');
            }
        });

        function updateUsernamePreview(value) {
            const preview = document.getElementById('username-preview');
            if (preview) preview.textContent = value || 'username';
        }

        // Delete account modal
        (function() {
            const modal = document.getElementById('delete-account-modal');
            const openBtn = document.getElementById('open-delete-account-modal');
            const cancelBtn = document.getElementById('cancel-delete-account');
            const confirmBtn = document.getElementById('confirm-delete-account');
            const passwordInput = document.getElementById('delete-account-password');
            const confirmationInput = document.getElementById('delete-account-confirmation');
            const errorBox = document.getElementById('delete-account-error');

            function showError(message) {
                errorBox.textContent = message;
                errorBox.classList.remove('hidden');
            }

            function openModal() {
                passwordInput.value = '';
                confirmationInput.value = '';
                errorBox.classList.add('hidden');
                modal.classList.remove('hidden');
                modal.classList.add('flex');
            }

            function closeModal() {
                modal.classList.add('hidden');
                modal.classList.remove('flex');
            }

            openBtn.addEventListener('click', openModal);
            cancelBtn.addEventListener('click', closeModal);
            modal.addEventListener('click', function(e) {
                if (e.target === modal) closeModal();
            });

            confirmBtn.addEventListener('click', async function() {
                errorBox.classList.add('hidden');
                confirmBtn.disabled = true;
                confirmBtn.textContent = 'Deleting...';
                try {
                    const response = await fetch('/api/account/delete-account.php', {
                        method: 'POST',
                        headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
                        body: new URLSearchParams({
                            <?php echo json_encode(CSRF_TOKEN_NAME); ?>: <?php echo json_encode(csrfToken()); ?>,
                            password: passwordInput.value,
                            confirmation: confirmationInput.value,
                        }),
                    });
                    const result = await response.json();
                    if (response.ok && result.success) {
                        window.location.href = '/?account_deleted=1';
                    } else {
                        showError(result.error || 'Something went wrong. Please try again.');
                    }
                } catch (err) {
                    showError('Network error. Please try again.');
                } finally {
                    confirmBtn.disabled = false;
                    confirmBtn.textContent = 'Delete my account';
                }
            });
        })();
    </script>

    <?php partial('footer'); ?>
</body>
</html>
